# Name:    PyHouse-ansible/roles/install-vnc/tasks/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-12-16
# Updated: 2017-12-16

# Install install and set up a vnc server on the computer

---

- name: Task-01 - install VNC server
  apt:
    name:               tightvncserver
    update_cache:       yes
    cache_valid_time:   3600

### END DBK
