# Name:    PyHouse-ansible/inventories/development/host_vars/pi-06-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2018-07-25
# Updated: 2018-07-25
#
# This pi is for development - do not use for anything production.
#
#

---

ansible_host:               192.168.9.16

pyh_hostname:               pi-06-ct
pyh_ipv4_ethernet_addr:     192.168.10.16
pyh_ipv4_wifi_addr:         192.168.9.16
pyh_ipv6_ethernet_addr:     :10:16
pyh_ipv6_wifi_addr:         :9:16
pyh_roles:                  pandora,pyhouse

# Overrides
pyh_ipv4_router_addr:           192.168.9.1
pyh_router_nameservers:         "192.168.9.1 8.8.8.8"
pyh_ipv6_network_prefix:        "2001:470:5:417:"

### END DBK
