# Name:    PyHouse-ansible/inventories/development/host_vars/pi-05-pp.yaml
# Author:  D. Brian Kimmel
# Created: 2017-12-12
# Updated: 2018-04-22
#
# This computer is for developing.
#
# It is not used for production so it may be reloaded at will.
#

--- 

ansible_host:               192.168.1.17

pyh_hostname:               pi-07-pp
pyh_ipv4_ethernet_addr:     192.168.2.17
pyh_ipv4_wifi_addr:         192.168.1.17
pyh_ipv6_ethernet_addr:     :2:17
pyh_ipv6_wifi_addr:         :1:17
pyh_roles:                  node-red

pyh_extra_apt_packages:
    - i2c-tools
    - python3
    - sqlite3

pyh_extra_nodered_nodes:
    - i2c
    - i2c-bus
    - node-red-contrib-timerswitch
    - node-red-contrib-mcp23017chip     # Requires i2c-bus
    - node-red-dashboard
    - node-red-node-sqlite
    # The following give compile errors (2018-04-24)
    #- node-mcp23017
    #- node-red-contrib-mcp23017         # requires node-mcp23017

### END DBK
