# Name    roles/update_system/tasks/update.yaml
# Updated: 2020-11-08
#
---

- name: Task-01(Update) - Info
  debug:
    msg:
      - " Role Update System"
      - "  Distribution: {{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}"
      - "     OS Family: {{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yaml"

- name: Task-02(Update) - set OS dependent variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.distribution }}.yaml'
    - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.os_family }}.yaml'

# Ignore errors if internet is down
- name: Task-03(Update) - Update and upgrade apt packages.
  ignore_errors: true # Ignore errors if internet is down
  apt:
    upgrade: 'True'
    update_cache: 'True'
    cache_valid_time: 3600

## sudo apt install python-pip python-dev python-setuptools python-virtualenv git libyaml-dev build-essential
- name: Task-04(Update) - Install needed apt packages.
  ignore_errors: true # Ignore errors if internet is down
  apt:
     name: "{{ begin_basic_package_list }}"
     state: present

### END DBK
