# Name:    PyHouse-ansible/group_vars/cannontrail/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-11-05
# Updated: 2017-11-05
#
# Variables for the Cannon Trail house.
#
# The vault variables are stored in group_vars/cannontrail/vault.yaml
#
# To encrypt / decript do one of the following:
#       ansible-vault encrypt group_vars/cannontrail/vault.yaml --vault-password-file ~/.vault-pass.txt
#       ansible-vault decrypt group_vars/cannontrail/vault.yaml --vault-password-file ~/.vault-pass.txt
#
# Keep the ~/.vault-pass.text file a secret.

---

pyh_access_points:      vault_pyh_access_points

pyh_router_address:     192.168.9.1
pyh_router_netmask:     255.255.240.0
pyh_router_prefix_len:  20
pyh_router_nameservers: "192.168.9.1 8.8.8.8"
pyh_domain:             ""

pyh_house_name:         cannontrail
pyh_house_latitude:     33.00000000
pyh_house_longitude:    -85.11111111
pyh_house_elevation:    777.00

### END DBK
