# Name:    PyHouse-ansible/group_vars/pyhouse.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-31
# Updated: 2017-10-31

---

# These packages are needed before we can install the PyHouse git repository
pyh_extra_apt_packages:
    - python3
    - python3-pip
    - python3-openssl
    - libffi-dev
    - libssl-dev
# sudo apt install libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev


pyh_extra_pip_packages:
    - aniso8601
    - astral
    - autobahn
    - jsonpickle
    - netaddr
    - netifaces
    - pyOpenSSL
    - python-dateutil
    - pyudev
    - service-identity
    - twisted
    #- athena
    #- idna
    #- nevow
    #- passlib
    #- pyasn1
    #- pycrypto
    #- pyserial
    #- pytz
    #- pyusb

### END DBK
