# Name:   install-wifi/tasks/main.yaml
---

- name: Install-WiFi-Task-01 - delete any new file created
  ignore_errors: true
  file:
    name: /etc/wpa_supplicant/wpa_supplicant.conf-new
    state: absent

- name: Install-WiFi-Task-02 - debug
  ignore_errors: true
  debug:
    msg:
      - "User: {{ vault_pyh_admin_user }}"
      - "AP:   {{ vault_pyh_access_points }}"

- name: Install-WiFi WiFi-Task-03 - Install the wpa_supplicant file
  ignore_errors: true
  template:
    src: ./wifi.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600

# - name: Install-WiFi-Task-04 - put wifi config in place
#   template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf
#   notify: reboot

### END DBK