# Name:    PyHouse-ansible/inventories/group_vars/pinkpoppy/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-11-05
# Updated: 2020-11-13
#
# Variables for the Pink Poppy house.

# The vault variables are stored in inventories/production/group_vars/pinkpoppy/vault.yaml
#
# To encrypt / decript do one of the following:
#       ansible-vault encrypt inventories/group_vars/pinkpoppy/vault.yaml --vault-password-file ~/.vault-pass.txt
#       ansible-vault decrypt inventories/group_vars/pinkpoppy/vault.yaml --vault-password-file ~/.vault-pass.txt
#
# Keep the ~/.vault-pass.text file a secret.

---

pyh_house_name:                 vault_pyh_house_name
pyh_house_latitude:             vault_pyh_house_latitude
pyh_house_longitude:            vault_pyh_house_longitude
pyh_house_elevation:            vault_pyh_house_elevation

# Used by role networking
wifi_access_points: vault_wifi_access_points
pyh_ipv4_router_addr:           vault_pyh_ipv4_router_addr
pyh_ipv4_router_netmask:        vault_pyh_ipv4_router_netmask
pyh_ipv4_router_prefix_len:     vault_pyh_ipv4_router_prefix_len
pyh_router_nameservers:         vault_pyh_router_nameservers
pyh_ipv6_network_prefix:        vault_pyh_ipv6_network_prefix
pyh_ipv6_network_prefix_len:    /64
hostname_domain: vault_hostname_domain

# Household Configurations
household_house_name: Pink Poppy
household_time_server: pi-05-pp

### END DBK
