# Name:    PyHouse-ansible/group_vars/raspi/vars.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-18
# Updated: 2017-10-20
#
# The vault variables are stored in group_vars/raspi/vault.yaml
#
# To encrypt / decript do one of the following:
#       ansible-vault encrypt group_vars/raspi/vault.yaml --vault-password-file ~/.vault-pass.txt
#       ansible-vault decrypt group_vars/raspi/vault.yaml --vault-password-file ~/.vault-pass.txt
#
# Keep the ~/.vault-pass.text file a secret.

---

#- include_vars:             ./vault.yaml
#- vars:
pyh_family:             Pi
pyh_domain:             ""

pyh_admin_user:         "{{ vault_pyh_admin_user }}"
pyh_admin_password:     "{{ vault_pyh_admin_password }}"
pyh_long_admin_name:    "{{ vault_pyh_long_admin_name }}"

pyh_pi_user:            "{{ vault_pyh_pi_user }}"
pyh_pi_password:        "{{ vault_pyh_pi_password }}"
pyh_long_pi_name:       "{{ vault_pyh_pi_admin_name }}" 

pyh_nodered_user:       "{{ vault_pyh_nodered_user }}"
pyh_nodered_password:   "{{ vault_pyh_nodered_password }}"
pyh_long_nodered_name:  "{{ vault_pyh_long_nodered_name }}"

pyh_in_setup:           yes
...

### END DBK
