# Name:    PyHouse-ansible/host_vars/pi-06-pp
# Author:  D. Brian Kimmel
# Created: 2018-06-19
# Updated: 2018-06-19
#
# This computer is for pandora
#

---

ansible_host:               192.168.9.16

pyh_hostname:               pi-06-ct
pyh_ipv4_ethernet_addr:     192.168.10.16
pyh_ipv4_wifi_addr:         192.168.9.16
pyh_ipv6_ethernet_addr:     :2:16
pyh_ipv6_wifi_addr:         :1:16
pyh_roles:                  pandora,pyhouse

### END DBK
