# Name:   roles/function_octoprint/vars/Debian.yaml
# Updated: 2020-12-03
#
#---

# cd ~
# sudo apt update
# sudo apt install python3-pip python3-dev python3-setuptools python3-venv git libyaml-dev build-essential
# mkdir OctoPrint && cd OctoPrint
# python3 -m venv venv
# source venv/bin/activate

octoprint_main_package_list:
   - build-essential
   - git
   - python3-pip
   - python3-setuptools
   - haproxy

octoprint_venv_os_package_list:
   - python3-dev
   - python3-venv


octoprint_camera_package_list:
   - subversion
   - libjpeg62-turbo-dev
   - imagemagick
   - ffmpeg
   - libv4l-dev
   - cmake

### END DBK
