# Name:    inventories/host_vars/pi-01-pp.yaml
# Updated: 2020-11-07
#
---
#
# Change the following definitions as needed:

ansible_host: 172.16.2.1
basic_hostname: pi-01-pp
wireguard_address: "10.12.14.101/24"

#usb_clone_drive_type: SSD-128GB
#usb_clone_drive_id: /dev/sda
#usb_storage_drive_type: Disk-4TB
#usb_storage_drive_id: /dev/sdb

# This pi is used for testing out ansible roles - no production uses.
#
host_functions:
   - function_mqtt
   - function_node_red
   - function_none

# ==============================
# The following should probably be left as defined.

admin_user_name: briank
basic_domain: ""
wireguard_endpoint: "{{ basic_hostname }}-wg"
hostname_hostname: "{{ basic_hostname }}"
hostname_domain: "{{ basic_domain | default('')}}"
ansible_ssh_user: "{{ admin_user_name }}"
host_key_checking: false

### END DBK
