# Name:    inventories/host_vars/pi-05-pp.yaml
# Updated: 2020-10-28

---
#
# Change the following definitions as needed:

ansible_host: 172.16.31.202
basic_hostname: pi-05-pp
wireguard_address: "10.12.14.105/24"

#usb_clone_drive_type: SSD-128GB
#usb_clone_drive_id: /dev/sda
#usb_storage_drive_type: Disk-4TB
#usb_storage_drive_id: /dev/sdb

host_functions:
  #- harden_linux
  - setup_house_proxy
  #- finalize

vpn_enabled: yes
vpn_zerotier_enabled: yes
vpn_wireguard_enabled: yes

admin_user_name: briank
basic_domain: ""
wireguard_endpoint: "{{ basic_hostname }}-wg"
hostname_hostname: "{{ basic_hostname }}"
hostname_domain: "{{ basic_domain | default('')}}"
ansible_ssh_user: "{{ admin_user_name }}"
host_key_checking: false

### END DBK
