# Name:    PyHouse-ansible/host_vars/pi-06-pp
# Updated: 2020-11-03
#
---

#
# Change the following definitions as needed:

ansible_host: 172.16.2.6
basic_hostname: pi-06-pp
wireguard_address: "10.12.14.106/24"

#usb_clone_drive_type: SSD-128GB
#usb_clone_drive_id: /dev/sda
#usb_storage_drive_type: Disk-4TB
#usb_storage_drive_id: /dev/sdb

host_functions:
   #- install_vnc
   #- setup_house_proxy
   - function_none

# ==============================
# The following should probably be left as defined.

admin_user_name: briank
basic_domain: ""
wireguard_endpoint: "{{ basic_hostname }}-wg"
hostname_hostname: "{{ basic_hostname }}"
hostname_domain: "{{ basic_domain | default('')}}"
ansible_ssh_user: "{{ admin_user_name }}"
host_key_checking: false

### END DBK
