# Name:    PyHouse-ansible/roles/default_config/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-12
# Updated: 2017-10-31
#
# This is the main playbook default config.
# Used to configure after one of the setup playbooks has run.

---

# Default variables that are shared by more than one role in the Playbook.

install_networking:     no
install_webserver:      no


# Install haproxy Load Balancer?
install_loadbalancer:   no

# Instal varnix proxy cache?
install_proxycache:     no

# Install munin monitoring?
install_muninnode:      no

# Install Nagios snmp server monitoring?
install_nagios:         no

# Install postfix mail server?
install_mailserver:     no

### END DBK
