# Name:     PyHouse-ansible/host_vars/nuc-01-ct
# Author:  D. Brian Kimmel
# Created: 2017-10-02
# Updated: 2017-11-01
#
# The Nuc that is in the living room at CT

---

ansible_host:               192.168.9.10

pyh_hostname:               nuc-01-ct
pyh_ipv4_ethernet_addr:     192.168.9.10
pyh_ipv4_wifi_addr:         no
pyh_ipv6_ethernet_addr:     :9:10
pyh_ipv6_wifi_addr:         :10:10
pyh_roles:                  mqtt

### END DBK
