# Name:     PyHouse-ansible/inventories/production/host_vars/nuc-01-pp.yaml
# Author:  D. Brian Kimmel
# Created: 2017-09-26
# Updated: 2017-11-01
#
# This is a master house computer.
#
# Mqtt.
# SNMP monitoring
# Nagios
#

---

ansible_host:           192.168.1.10

pyh_hostname:           nuc-01-pp
pyh_ethernet_ip:        192.168.1.10
pyh_wifi_ip:            192.168.2.10
pyh_roles:              mqtt

### END DBK
