# Name:    PyHouse-ansible/host_vars/pi-05-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2017-11-01

---

ansible_host:           192.168.9.15

pyh_hostname:           pi-05-ct
pyh_ethernet_ip:        192.168.9.45
pyh_wifi_ip:            192.168.9.15
pyh_roles:              pyhouse

### END DBK
