# Name:    PyHouse-ansible/inventories/production/host_vars/pi-01-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-09-29
# Updated: 2018-04-07










---

ansible_host:               192.168.9.11

pyh_hostname:               pi-01-ct
pyh_ipv4_ethernet_addr:     192.168.10.11
pyh_ipv4_wifi_addr:         192.168.9.11
pyh_ipv6_ethernet_addr:     :10:11
pyh_ipv6_wifi_addr:         :9:11
pyh_roles:                  pyhouse

pyh_extra_apt_packages:
    - python3

### END DBK
