# Name:    PyHouse-ansible/inventories/production/host_vars/pi-05-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2018-04-07
#
# This pi is for development - do not use for anything production.
#
# Raspberry Pi Model: 3B; Embest, China  RAM: 1024
#





---

ansible_host:               192.168.9.15

pyh_hostname:               pi-05-ct
pyh_ipv4_ethernet_addr:     192.168.10.15
pyh_ipv4_wifi_addr:         192.168.9.15
pyh_ipv6_ethernet_addr:     :10:15
pyh_ipv6_wifi_addr:         :9:15
pyh_roles:                  pyhouse

### END DBK
