# Name:    PyHouse-ansible/inventories/production/host_vars/pi-07-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2018-04-07

---

ansible_host:               192.168.9.17

pyh_hostname:               pi-07-ct
pyh_ipv4_ethernet_addr:     192.168.10.17
pyh_ipv4_wifi_addr:         192.168.9.17
pyh_ipv6_ethernet_addr:     :10:17
pyh_ipv6_wifi_addr:         :9:17
pyh_roles:                  pyhouse

pyh_extra_apt_packages:
    - git

### END DBK
