# Name:    PyHouse-ansible/host_vars/pi-04-pp
# Author:  D. Brian Kimmel
# Created: 2017-09-28
# Updated: 2017-11-22

# Model B+     512M ram   Jessie      armv6l


# This computer is located in the garage of Pink Poppy.
# It controls:
#   Front Drip Irrigation
#   Lawn Irrigation
#   Rear Drip
#   Citrus Drip
#   Pool Level and Fill

---

ansible_host:               192.168.1.14

pyh_hostname:               pi-04-pp
pyh_ipv4_ethernet_addr:     192.168.2.14
pyh_ipv4_wifi_addr:         192.168.1.14
pyh_ipv6_ethernet_addr:     :2:14
pyh_ipv6_wifi_addr:         :1:14
pyh_roles:                  node-red

pyh_extra_apt_packages:
    - sqlite3
    - i2c-tools

pyh_extra_nodered_nodes:
    - i2c
    - i2c-bus
    - node-red-dashboard
    - node-red-node-sqlite
    - node-red-contrib-i2c
    - node-red-contrib-timerswitch

### END DBK
