# Name:    PyHouse-ansible/roles/install-octoprint/meta/main.yaml
# Author:  D. Brian Kimmel
# Created: 2018-07-01
# Updated: 2018-07-01
#
# This role will install  * * * O C T O P R I N T * * *  on a raspberry pi computer.
#
# Be sure to edit group_vars/octoprint.yaml


---

galaxy_info:
  author: Chris Church
  description: Configure and update a Python virtualenv.
  company: "Nine More Minutes, Inc."
  license: BSD
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - '6'
        - '7'
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - development
    - packaging
    
allow_duplicates: true

#dependencies:
#  - install-basic-system

### END DBK
