# Name:    PyHouse-ansible/inventories/raspberrypi/host_vars/pi-setup.yaml
# Author:  D. Brian Kimmel
# Created: 2017-11-30
# Updated: 2017-12-06

# This is the host_vars file for setting up a raspberry pi for home automation use.

# When each PI boots with ethernet, a new ip is set up = put that IP in below.
# Wifi will not work since it has not been set up to use the house access points yet.
# Only the "pi" user exists at first.

---

# These must be changed
ansible_host:           192.168.1.134
pyh_hostname:           pi-11-pp
pyh_ethernet_ip:        192.168.2.21
pyh_wifi_ip:            192.168.1.21
pyh_roles:              setup

pyh_router_address:         192.168.1.1
pyh_router_prefix_len:      20
vault_pyh_access_points:    {'PinkPoppy-Guest': 'MarciaBrian'}
pyh_admin_user_groups:      adm,dialout,sudo,audio,video,plugdev,input,netdev,spi,i2c,gpio
pyh_router_nameservers:     "192.168.1.1 8.8.8.8"

# You should not change the following:
pyh_domain:             ""
pyh_in_setup:           yes

ansible_user:           pi
ansible_ssh_pass:       raspberry

### END DBK
