# Name: roles/dispatch_function_install/tasks/dispatch.yaml
# Updated: 2020-11-26
#
---

- name: Task-01(Dispatch) - Dispatch
  debug:
    msg: |
      "--- Role: Dispatch_function_install ---"
      "   Host Functions: {{ host_functions }}"

- name: Task-02(Dispatch) - do the next step in host_functions (defined in the given host_vars yaml file).
  ignore_errors: true
  include_role:
    name: "{{ dispatch_item }}"
  loop: "{{ host_functions }}"
  loop_control:
    loop_var: dispatch_item


#- name: Task-03(Dispatch) - Install Pandora step is next
#  include_role:
#    name: install_pandora
#  when: selected == 'pandora'

#- name: Task-04(Dispatch) - Intall PyHouse step is next
#  include_role:
#    name: install_pyhouse
#  when: selected == 'pyhouse'

#- name: Task-05(Dispatch) - Install Vnc step is next
#  include_role:
#    name: install_vnc
#  when: dispatch_item == 'vnc'

#- name: Task-06(Dispatch) - Install Wireguard step is next
#  include_role:
#    name: install_wireguard
#  when: selected == 'wireguard'

### END DBK
