# Name:   roles/install_basic_system/defaults/main.yaml
# Updated: 2020-10-07
#
---

default_timezone: "US/Eastern"

test_default_token: 'Test Default Token'

# Namespace 'basic'
#
basic_reboot_enabled: true
basic_update_enabled: yes
basic_avahi_enabled: yes
basic_timezone: US/Eastern
basic_backup_enabled: yes
basic_dyndns_enabled: yes
basic_firewall_enabled: yes

# apt packages used on all raspberry pi computers
basic_apt_package_list:
   - git
   - python3-pip
   - python3-dev
   - python3-setuptools
   - python3-venv
   - tree
  


### END DBK
