# Name:    PyHouse-ansible/inventories/setup-pi/group_vars/all/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-12-05
# Updated: 2018-04-22
#
# The vault variables are stored in inventories/setup-pi/group_vars/all/vault.yaml
#
# To encrypt / decript do one of the following:
#       ansible-vault encrypt inventories/setup-pi/group_vars/all/vault.yaml --vault-password-file ~/.vault-pass.txt
#       ansible-vault decrypt inventories/setup-pi/group_vars/all/vault.yaml --vault-password-file ~/.vault-pass.txt
#
# Keep the ~/.vault-pass.txt file a secret.

---

pyh_admin_user:             "{{ vault_pyh_admin_user }}"
pyh_admin_password:         "{{ vault_pyh_admin_password }}"
pyh_long_admin_name:        "{{ vault_pyh_long_admin_name }}"

pyh_pi_user:                "{{ vault_pyh_pi_user }}"
pyh_pi_password:            "{{ vault_pyh_pi_password }}"
pyh_long_pi_name:           "{{ vault_pyh_pi_admin_name }}" 

pyh_nodered_user:           "{{ vault_pyh_nodered_user }}"
pyh_nodered_password:       "{{ vault_pyh_nodered_password }}"
pyh_long_nodered_name:      "{{ vault_pyh_long_nodered_name }}"

pyh_pyhouse_user:           "{{ vault_pyh_pyhouse_user }}"
pyh_pyhouse_password:       "{{ vault_pyh_pyhouse_password }}"
pyh_long_pyhouse_name:      "{{ vault_pyh_long_pyhouse_name }}"

# Used by role 'networking'
#pyh_access_points:              vault_pyh_access_points
pyh_access_points:             "{{ vault_pyh_access_points }}"
pyh_ipv4_router_addr:           192.168.1.1
pyh_ipv4_router_prefix_len:     20
pyh_ipv4_router_netmask:        255.255.240.0
pyh_ipv6_network_prefix:        "2001:470:5:417:"
pyh_ipv6_network_prefix_len:    /64
pyh_router_nameservers:         "192.168.1.1 8.8.8.8"
pyh_domain:                     ""

### END DBK
