# Name:    PyHouse-ansible/roles/common/tasks/bluetooth.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2017-10-01
#
# Called from roles/common/tasks/network.yaml

---
# Firewall

### END DBK
