# Name:    PyHouse-ansible/roles/firewall/tasks/firewall.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2017-10-12
#
# Called from common/network.yaml
# Firewall


# NOTE: This playbook *adds* rules.
# It does not delete existing rules.

---


- name: Enable ufw
  ufw: state=enabled policy=allow

- name: Disable default in
  ufw: direction=incoming policy=deny

- name: Port 33 (SSH) is open
  ufw: rule=limit name=OpenSSH

- name: Port 80 (HTTP) is open
  ufw: rule=allow port=80 proto=tcp

- name: Port 443 (HTTPS) is open
  ufw: rule=allow port=443 proto=tcp

#- name: 4949 (munin-node) is open to monitor(s)
#  when: install_muninnode|default(True)
#  ufw: rule=allow port=4949 proto=tcp from_ip={{ item }}
#  with_items: muninnode_query_ips|default([])

### END DBK
