# Name:    PyHouse-ansible/roles/common/tasks/wifi.yaml
# Author:  D. Brian Kimmel
# Created: 2017-09-18
# Updated: 2017-10-08
#
# Called from roles/common/tasks/network.yaml

---

#- name: wifi-task-01A - Imports
#  include: roles/common/tasks/avahi.yaml

#- name: wifi-task-01B- Imports
#  include: roles/common/tasks/pkg_mgr.yaml


# The dir /etc/wpa_supplicant exists on raspis but not on a nuc with no wifi card installed.
- name: wifi-task-01 - Check if path exists
  stat:
    path:       "/etc/wpa_supplicant"
  register: wpa_dir_exists

- name: wifi-task-02 - Install the wpa_supplicant file
  template:
    src:        ./wifi.j2
    dest:       /etc/wpa_supplicant/wpa_supplicant.conf
    owner:      root
    group:      root
    mode:       0600
  when: wpa_dir_exists.stat.exists

### END DBK
