# Name:    PyHouse-ansible/roles/package-management/tasks/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-11-01
# Updated: 2019-08-07
#
# Use the proper package management and update to the current level

---

- name: Task-01 - Apt if a Debian type distribution
  include_tasks: "setup-{{ansible_os_family}}.yaml"

### END DBK
