# Name:   roles/setup_house_proxy/defaults/main.yaml
# Updated: 2020-10-27
#
---
# To allow this role to be turned off.
house_proxy_role_enabled: true

house_main_proxy_html_dir: /var/www/html/

house_proxy_houses:
   - Cannon Trail
   - Pink Poppy

house_proxy_services:
   - HomeAssistant
   - Octoprint
   - Sonoff
   - Node-Red
   - Pi-Hole
   - Pandora
   - Mopidy
   - PyHouse
   - Mqtt
   - Monitor

### END DBK
