# Name:    PyHouse-ansible/inventories/group_vars/all/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-11-22
# Updated: 2017-11-22

---

- import_vars:  '../../../../group_vars/all/main.yaml'

### END DBK
