# Name:   roles/a_begin/defaults/main.yaml
# Updated: 2020-11-08
#
---
# defaults file for a_begin

# To allow this role to be turned off.
begin_role_enabled: true

begin_roles_to_run:
   - update_system
   - setup_avahi
   - setup_hostname
   - setup_security
   - setup_ssh
   - setup_time_service
   - setup_usb_boot

# packages used on all computers - by distribution, release type.
begin_basic_package_list: []

### END DBK
