# Name:    PyHouse-ansible/host_vars/pi-01-pp.yaml
# Author:  D. Brian Kimmel
# Created: 2017-09-26
# Updated: 2017-11-01

---

ansible_host:           192.168.1.11

pyh_hostname:           pi-01-pp
pyh_ethernet_ip:        192.168.1.41
pyh_wifi_ip:            192.168.1.11
pyh_roles:              pyhouse

pyh_extra_apt_packages:
    - git

### END DBK
