# Name:    PyHouse-ansible/host_vars/pi-07-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2017-10-22

---

ansible_host:           192.168.9.17

pyh_hostname:           pi-07-ct
pyh_family:             Pi
pyh_ethernet_ip:        192.168.9.47
pyh_wifi_ip:            192.168.9.17
pyh_roles:              pyhouse

### END DBK
