# Name:    PyHouse-ansible/host_vars/pi-08-pp
# Author:  D. Brian Kimmel
# Created: 2017-09-28
# Updated: 2017-11-18

# This computer runs Octopi and controls my 3D printer.

---

ansible_host:           192.168.1.18

pyh_hostname:           pi-08-pp
pyh_ethernet_ip:        192.168.2.18
pyh_wifi_ip:            192.168.1.18
pyh_roles:              octoprint

### END DBK
