# Name:    PyHouse-ansible/host_vars/pi-05-pp
# Author:  D. Brian Kimmel
# Created: 2017-11-06
# Updated: 2017-11-08
#
# This computer is for
#

---

ansible_host:           192.168.1.15

pyh_hostname:           pi-05-pp
pyh_ethernet_ip:        192.168.2.15
pyh_wifi_ip:            192.168.1.15
pyh_roles:              none

### END DBK
