# Name:    PyHouse-ansible/host_vars/pi-02-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-09-29
# Updated: 2017-10-31

---

ansible_host:           192.168.9.12

pyh_hostname:           pi-02-ct
pyh_family:             Pi
pyh_ethernet_ip:        192.168.9.42
pyh_wifi_ip:            192.168.9.12
pyh_roles:              nodered,pyhouse,mqtt

pyh_extra_apt_packages:
    - sqlite3

pyh_extra_nodered_nodes:
    - node-red-dashboard
    - node-red-node-sqlite
    - node-red-contrib-timerswitch

### END DBK
