# Name:    PyHouse-ansible/host_vars/pi-01-pp
# Author:  D. Brian Kimmel
# Created: 2017-09-26
# Updated: 2017-09-28

---

ansible_host:           192.168.1.12

pyh_hostname:           pi-02-pp
pyh_family:             Pi
pyh_ethernet_ip:        192.168.1.42
pyh_wifi_ip:            192.168.1.12
pyh_roles:              nodered

### END DBK
