# Name:    PyHouse-ansible/host_vars/pi-02-pp
# Author:  D. Brian Kimmel
# Created: 2017-09-26
# Updated: 2017-11-06

---

ansible_host:           192.168.1.12

pyh_hostname:           pi-02-pp
pyh_ethernet_ip:        192.168.1.42
pyh_wifi_ip:            192.168.1.12
pyh_roles:              nodered

pyh_extra_apt_packages:
    - sqlite3

pyh_extra_nodered_nodes:
    - i2c
    - canvas-gauges
    - node-red-contrib-i2c
    - node-red-contrib-os
    - node-red-contrib-timerswitch
    - node-red-dashboard
    - node-red-node-email
    - node-red-node-ping
    - node-red-node-snmp

#
#    - node-red-node-sqlite

# This is a part of the johnny-five system.
#    - node-red-contrib-gpio

### END DBK
