# Name:    PyHouse-ansible/host_vars/pi-06-pp
# Author:  D. Brian Kimmel
# Created: 2017-11-08
# Updated: 2017-11-08
#
# This computer is for
#

---

ansible_host:           192.168.1.16

pyh_hostname:           pi-06-pp
pyh_ethernet_ip:        192.168.1.46
pyh_wifi_ip:            192.168.1.16
pyh_roles:              none

### END DBK
