# Name:    PyHouse-ansible/host_vars/pi-10-pp
# Author:  D. Brian Kimmel
# Created: 2017-09-26
# Updated: 2017-11-09
#
# This computer is for backup pyhouse.
# It has an attached Insteon PLM for controlling lighting.
#

---

ansible_host:           192.168.1.20

pyh_hostname:           pi-10-pp
pyh_ethernet_ip:        192.168.2.20
pyh_wifi_ip:            192.168.1.20
pyh_roles:              pyhouse

pyh_extra_apt_packages:
    - git

### END DBK
