# Name:    PyHouse-ansible/host_vars/pi-11-ct.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-01
# Updated: 2017-10-01

---

vars:
  pyh_family:      "Pi"
  pyh_ethernet_ip: 192.168.9.51
  pyh_wifi_ip:     192.168.9.21
  pyh_roles:       "NodeRed"

### END DBK
