# Name:    PyHouse-ansible/host_vars/pi-setup.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-12
# Updated: 2017-10-23

# This is the hosts file for setting up a raspberry pi for my use.

# When each PI boots with ethernet a new ip is set up = put that IP in below.
# Wifi will not work since it has not been set up to use my access points yet.
# Only the "pi" user exists at first.

---

# These must be changed
ansible_host:           192.168.9.43
pyh_hostname:           pi-03-ct
pyh_ethernet_ip:        192.168.9.43
pyh_wifi_ip:            192.168.9.13
pyh_roles:              pyhouse

# You should not change the following:
pyh_family:             Pi
pyh_domain:             ""
pyh_in_setup:           yes

### END DBK
