# Name:    PyHouse-ansible/inventories/production/group_vars/all/main.yaml
# Author:  D. Brian Kimmel
# Created: 2017-10-23
# Updated: 2019-08-07
#
# The vault variables are stored in group_vars/all/vault.yaml
# Keep the ~/.vault-pass.txt file a secret.
#
# To encrypt / decript do one of the following:
#       ansible-vault encrypt group_vars/all/vault.yaml --vault-password-file ~/.vault-pass.txt
#       ansible-vault decrypt group_vars/all/vault.yaml --vault-password-file ~/.vault-pass.txt

---

ansible_python_interpreter: /usr/bin/python3

pyh_domain: ""

pyh_admin_user: "{{ vault_pyh_admin_user }}"
pyh_admin_password: "{{ vault_pyh_admin_password }}"
pyh_long_admin_name: "{{ vault_pyh_long_admin_name }}"

pyh_pi_user: "{{ vault_pyh_pi_user }}"
pyh_pi_password: "{{ vault_pyh_pi_password }}"
pyh_long_pi_name: "{{ vault_pyh_pi_admin_name }}" 

pyh_nodered_user: "{{ vault_pyh_nodered_user }}"
pyh_nodered_password: "{{ vault_pyh_nodered_password }}"
pyh_long_nodered_name: "{{ vault_pyh_long_nodered_name }}"

pyh_pyhouse_user: "{{ vault_pyh_pyhouse_user }}"
pyh_pyhouse_password: "{{ vault_pyh_pyhouse_password }}"
pyh_long_pyhouse_name: "{{ vault_pyh_long_pyhouse_name }}"

pyh_octoprint_user: "octo"
pyh_octoprint_password: "{{ vault_pyh_admin_password }}"
pyh_long_octoprint_name: "Octoprint"

# Networking
pyh_ipv4_router_prefix_len: 20

### END DBK
